### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by comonier** [q1zZu/q1zZ-DiscordRewards#21]
Console log: https://paste.ofcode.org/688JDyEDgRPMfWkF78QHKQ
i guess it was about config mysql database [done]
new issue: https://paste.ofcode.org/39MC6QWWXFHp4hQrcZ9RkmQ

https://paste.ofcode.org/zXgmxEvQNyArHLLHwGPyj7

**Comment by q1zZu** [comment]
Fixed.
